id = "gent"
name = "Gent"
version = "0.1.0"
schema_version = 1
authors = ["Ozan"]
description = "Syntax highlighting for the Gent programming language"
repository = "https://github.com/ozankasikci/zed-gent"

[grammars.gent]
repository = "https://github.com/ozankasikci/tree-sitter-gent"
rev = "487797e2153f4a2c13e114d93cdbb902b817614f"
